# build image and push to docker hub
# deploy to alibaba cloud(uncompleted)

trigger:
  branches:
    include:
      - master
variables:
  TAG: 1.0.0-alpha.1
  TESTTAG: test

stages:
  - stage: Build
    jobs:
      - job: build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo $(Build.SourceBranch)
              git describe
               ##vso[task.setvariable variable=TESTTAG]git describe
      - job: test
        pool:
          vmImage: 'ubuntu-latest'
          steps:
            - script: |
                echo $(TESTTAG)
#          - task: Docker@2
#            displayName: Login to Docker Hub
#            inputs:
#              command: login
#              containerRegistry: DockerHub
#          - task: Docker@2
#            displayName: Build and Push
#            inputs:
#              command: buildAndPush
#              repository: analyse4/digimon
#              tags: $(TAG)
#          # SSH
#          # Run shell commands or a script on a remote machine using SSH
#          - task: SSH@0
#            inputs:
#              sshEndpoint: alibabacloud-ecs-1
#              runOptions: 'commands' # Options: commands, script, inline
#              commands: mkdir -p /root/test/test # Required when runOptions == Commands
#              #scriptPath: # Required when runOptions == Script
#              #inline: # Required when runOptions == Inline
#              #args: # Optional
#              #failOnStdErr: true # Optional

