// Code generated by protoc-gen-go. DO NOT EDIT.
// source: digimon.proto

package pbprotocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DigimonIdentity int32

const (
	DigimonIdentity_AGUMON          DigimonIdentity = 0
	DigimonIdentity_GREYMON         DigimonIdentity = 1
	DigimonIdentity_SKULLGREYMON    DigimonIdentity = 2
	DigimonIdentity_WARGREYMON      DigimonIdentity = 3
	DigimonIdentity_GABUMON         DigimonIdentity = 4
	DigimonIdentity_GARURUMON       DigimonIdentity = 5
	DigimonIdentity_WEREGARURUMON   DigimonIdentity = 6
	DigimonIdentity_METALGARURUMON  DigimonIdentity = 7
	DigimonIdentity_BIYOMON         DigimonIdentity = 8
	DigimonIdentity_BIRDRAMON       DigimonIdentity = 9
	DigimonIdentity_GARUDAMON       DigimonIdentity = 10
	DigimonIdentity_TENTOMON        DigimonIdentity = 11
	DigimonIdentity_KABUTERIMON     DigimonIdentity = 12
	DigimonIdentity_MEGAKABUTERIMON DigimonIdentity = 13
	DigimonIdentity_PALMON          DigimonIdentity = 14
	DigimonIdentity_TOGEMON         DigimonIdentity = 15
	DigimonIdentity_LILLYMON        DigimonIdentity = 16
	DigimonIdentity_GOMAMON         DigimonIdentity = 17
	DigimonIdentity_IKKAKUMON       DigimonIdentity = 18
	DigimonIdentity_ZUDOMON         DigimonIdentity = 19
	DigimonIdentity_PATAMON         DigimonIdentity = 20
	DigimonIdentity_ANGEMON         DigimonIdentity = 21
	DigimonIdentity_MAGNAANGEMON    DigimonIdentity = 22
	DigimonIdentity_SALAMON         DigimonIdentity = 23
	DigimonIdentity_GATOMON         DigimonIdentity = 24
	DigimonIdentity_ANGEWOMON       DigimonIdentity = 25
)

var DigimonIdentity_name = map[int32]string{
	0:  "AGUMON",
	1:  "GREYMON",
	2:  "SKULLGREYMON",
	3:  "WARGREYMON",
	4:  "GABUMON",
	5:  "GARURUMON",
	6:  "WEREGARURUMON",
	7:  "METALGARURUMON",
	8:  "BIYOMON",
	9:  "BIRDRAMON",
	10: "GARUDAMON",
	11: "TENTOMON",
	12: "KABUTERIMON",
	13: "MEGAKABUTERIMON",
	14: "PALMON",
	15: "TOGEMON",
	16: "LILLYMON",
	17: "GOMAMON",
	18: "IKKAKUMON",
	19: "ZUDOMON",
	20: "PATAMON",
	21: "ANGEMON",
	22: "MAGNAANGEMON",
	23: "SALAMON",
	24: "GATOMON",
	25: "ANGEWOMON",
}

var DigimonIdentity_value = map[string]int32{
	"AGUMON":          0,
	"GREYMON":         1,
	"SKULLGREYMON":    2,
	"WARGREYMON":      3,
	"GABUMON":         4,
	"GARURUMON":       5,
	"WEREGARURUMON":   6,
	"METALGARURUMON":  7,
	"BIYOMON":         8,
	"BIRDRAMON":       9,
	"GARUDAMON":       10,
	"TENTOMON":        11,
	"KABUTERIMON":     12,
	"MEGAKABUTERIMON": 13,
	"PALMON":          14,
	"TOGEMON":         15,
	"LILLYMON":        16,
	"GOMAMON":         17,
	"IKKAKUMON":       18,
	"ZUDOMON":         19,
	"PATAMON":         20,
	"ANGEMON":         21,
	"MAGNAANGEMON":    22,
	"SALAMON":         23,
	"GATOMON":         24,
	"ANGEWOMON":       25,
}

func (x DigimonIdentity) String() string {
	return proto.EnumName(DigimonIdentity_name, int32(x))
}

func (DigimonIdentity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{0}
}

type LoginReq_LoginType int32

const (
	LoginReq_Visitor  LoginReq_LoginType = 0
	LoginReq_PassWord LoginReq_LoginType = 1
)

var LoginReq_LoginType_name = map[int32]string{
	0: "Visitor",
	1: "PassWord",
}

var LoginReq_LoginType_value = map[string]int32{
	"Visitor":  0,
	"PassWord": 1,
}

func (x LoginReq_LoginType) String() string {
	return proto.EnumName(LoginReq_LoginType_name, int32(x))
}

func (LoginReq_LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{2, 0}
}

type RoomInfo_RoomType int32

const (
	RoomInfo_TWO RoomInfo_RoomType = 0
)

var RoomInfo_RoomType_name = map[int32]string{
	0: "TWO",
}

var RoomInfo_RoomType_value = map[string]int32{
	"TWO": 0,
}

func (x RoomInfo_RoomType) String() string {
	return proto.EnumName(RoomInfo_RoomType_name, int32(x))
}

func (RoomInfo_RoomType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{5, 0}
}

type MsgPack struct {
	Router               string   `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPack) Reset()         { *m = MsgPack{} }
func (m *MsgPack) String() string { return proto.CompactTextString(m) }
func (*MsgPack) ProtoMessage()    {}
func (*MsgPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{0}
}

func (m *MsgPack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPack.Unmarshal(m, b)
}
func (m *MsgPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPack.Marshal(b, m, deterministic)
}
func (m *MsgPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPack.Merge(m, src)
}
func (m *MsgPack) XXX_Size() int {
	return xxx_messageInfo_MsgPack.Size(m)
}
func (m *MsgPack) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPack.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPack proto.InternalMessageInfo

func (m *MsgPack) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *MsgPack) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BaseAck struct {
	Result               int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseAck) Reset()         { *m = BaseAck{} }
func (m *BaseAck) String() string { return proto.CompactTextString(m) }
func (*BaseAck) ProtoMessage()    {}
func (*BaseAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{1}
}

func (m *BaseAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseAck.Unmarshal(m, b)
}
func (m *BaseAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseAck.Marshal(b, m, deterministic)
}
func (m *BaseAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseAck.Merge(m, src)
}
func (m *BaseAck) XXX_Size() int {
	return xxx_messageInfo_BaseAck.Size(m)
}
func (m *BaseAck) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseAck.DiscardUnknown(m)
}

var xxx_messageInfo_BaseAck proto.InternalMessageInfo

func (m *BaseAck) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *BaseAck) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginReq struct {
	Username             string             `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string             `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type                 LoginReq_LoginType `protobuf:"varint,3,opt,name=type,proto3,enum=pbprotocol.LoginReq_LoginType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetType() LoginReq_LoginType {
	if m != nil {
		return m.Type
	}
	return LoginReq_Visitor
}

type PlayerInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{3}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type LoginAck struct {
	Base                 *BaseAck    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,2,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{4}
}

func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (m *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(m, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetBase() *BaseAck {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LoginAck) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type RoomInfo struct {
	RoomId               uint64            `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Type                 RoomInfo_RoomType `protobuf:"varint,2,opt,name=type,proto3,enum=pbprotocol.RoomInfo_RoomType" json:"type,omitempty"`
	IsStart              bool              `protobuf:"varint,3,opt,name=IsStart,proto3" json:"IsStart,omitempty"`
	CurrentPlayerNum     uint32            `protobuf:"varint,4,opt,name=current_player_num,json=currentPlayerNum,proto3" json:"current_player_num,omitempty"`
	PlayerInfos          []*PlayerInfo     `protobuf:"bytes,5,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{5}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomId() uint64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomInfo) GetType() RoomInfo_RoomType {
	if m != nil {
		return m.Type
	}
	return RoomInfo_TWO
}

func (m *RoomInfo) GetIsStart() bool {
	if m != nil {
		return m.IsStart
	}
	return false
}

func (m *RoomInfo) GetCurrentPlayerNum() uint32 {
	if m != nil {
		return m.CurrentPlayerNum
	}
	return 0
}

func (m *RoomInfo) GetPlayerInfos() []*PlayerInfo {
	if m != nil {
		return m.PlayerInfos
	}
	return nil
}

// join room
type JoinRoomReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{6}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

type JoinRoomAck struct {
	Base                 *BaseAck  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	RoomInfo             *RoomInfo `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoomAck) Reset()         { *m = JoinRoomAck{} }
func (m *JoinRoomAck) String() string { return proto.CompactTextString(m) }
func (*JoinRoomAck) ProtoMessage()    {}
func (*JoinRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{7}
}

func (m *JoinRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomAck.Unmarshal(m, b)
}
func (m *JoinRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomAck.Marshal(b, m, deterministic)
}
func (m *JoinRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomAck.Merge(m, src)
}
func (m *JoinRoomAck) XXX_Size() int {
	return xxx_messageInfo_JoinRoomAck.Size(m)
}
func (m *JoinRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomAck proto.InternalMessageInfo

func (m *JoinRoomAck) GetBase() *BaseAck {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *JoinRoomAck) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

type StartGameAck struct {
	Identity             DigimonIdentity `protobuf:"varint,1,opt,name=identity,proto3,enum=pbprotocol.DigimonIdentity" json:"identity,omitempty"`
	RoomInfo             *RoomInfo       `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StartGameAck) Reset()         { *m = StartGameAck{} }
func (m *StartGameAck) String() string { return proto.CompactTextString(m) }
func (*StartGameAck) ProtoMessage()    {}
func (*StartGameAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f35044cfecd686d, []int{8}
}

func (m *StartGameAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameAck.Unmarshal(m, b)
}
func (m *StartGameAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameAck.Marshal(b, m, deterministic)
}
func (m *StartGameAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameAck.Merge(m, src)
}
func (m *StartGameAck) XXX_Size() int {
	return xxx_messageInfo_StartGameAck.Size(m)
}
func (m *StartGameAck) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameAck.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameAck proto.InternalMessageInfo

func (m *StartGameAck) GetIdentity() DigimonIdentity {
	if m != nil {
		return m.Identity
	}
	return DigimonIdentity_AGUMON
}

func (m *StartGameAck) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbprotocol.DigimonIdentity", DigimonIdentity_name, DigimonIdentity_value)
	proto.RegisterEnum("pbprotocol.LoginReq_LoginType", LoginReq_LoginType_name, LoginReq_LoginType_value)
	proto.RegisterEnum("pbprotocol.RoomInfo_RoomType", RoomInfo_RoomType_name, RoomInfo_RoomType_value)
	proto.RegisterType((*MsgPack)(nil), "pbprotocol.MsgPack")
	proto.RegisterType((*BaseAck)(nil), "pbprotocol.BaseAck")
	proto.RegisterType((*LoginReq)(nil), "pbprotocol.LoginReq")
	proto.RegisterType((*PlayerInfo)(nil), "pbprotocol.PlayerInfo")
	proto.RegisterType((*LoginAck)(nil), "pbprotocol.LoginAck")
	proto.RegisterType((*RoomInfo)(nil), "pbprotocol.RoomInfo")
	proto.RegisterType((*JoinRoomReq)(nil), "pbprotocol.JoinRoomReq")
	proto.RegisterType((*JoinRoomAck)(nil), "pbprotocol.JoinRoomAck")
	proto.RegisterType((*StartGameAck)(nil), "pbprotocol.StartGameAck")
}

func init() { proto.RegisterFile("digimon.proto", fileDescriptor_9f35044cfecd686d) }

var fileDescriptor_9f35044cfecd686d = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xda, 0x4c,
	0x14, 0x8d, 0x81, 0x80, 0xb9, 0xe6, 0xc7, 0x19, 0xf2, 0x25, 0x7c, 0xad, 0x5a, 0x21, 0x2f, 0x5a,
	0x54, 0x55, 0x91, 0x42, 0x54, 0xa5, 0x5d, 0x0e, 0xc2, 0x42, 0x2e, 0xe6, 0x47, 0x13, 0x53, 0x94,
	0x6e, 0x22, 0x07, 0x3b, 0xc8, 0x0a, 0x78, 0x1c, 0xdb, 0xa8, 0xa2, 0xaf, 0xd1, 0x7d, 0x1f, 0xb1,
	0xcf, 0x50, 0xcd, 0xb5, 0x8d, 0x51, 0x55, 0x55, 0x6a, 0x77, 0xf7, 0xdc, 0xdf, 0x73, 0x8e, 0x3d,
	0x50, 0x77, 0xbc, 0x95, 0xb7, 0xe1, 0xfe, 0x45, 0x10, 0xf2, 0x98, 0x13, 0x08, 0xee, 0x31, 0x58,
	0xf2, 0xb5, 0xf6, 0x0e, 0x2a, 0xe3, 0x68, 0x35, 0xb3, 0x97, 0x8f, 0xe4, 0x0c, 0xca, 0x21, 0xdf,
	0xc6, 0x6e, 0xd8, 0x96, 0x3a, 0x52, 0xb7, 0xca, 0x52, 0x44, 0x08, 0x94, 0x1c, 0x3b, 0xb6, 0xdb,
	0x85, 0x8e, 0xd4, 0xad, 0x31, 0x8c, 0xb5, 0x2b, 0xa8, 0xf4, 0xed, 0xc8, 0xa5, 0xc9, 0x18, 0x73,
	0xa3, 0xed, 0x3a, 0xc6, 0xb1, 0x22, 0x4b, 0x11, 0x51, 0xa1, 0x38, 0x8e, 0x56, 0x38, 0x55, 0x65,
	0x22, 0xd4, 0xbe, 0x4b, 0x20, 0x9b, 0x7c, 0xe5, 0xf9, 0xcc, 0x7d, 0x22, 0xcf, 0x40, 0xde, 0x46,
	0x6e, 0xe8, 0xdb, 0x1b, 0x37, 0xbd, 0xb7, 0xc7, 0xa2, 0x16, 0xd8, 0x51, 0xf4, 0x85, 0x87, 0x4e,
	0x3a, 0xbf, 0xc7, 0xa4, 0x07, 0xa5, 0x78, 0x17, 0xb8, 0xed, 0x62, 0x47, 0xea, 0x36, 0x7a, 0x2f,
	0x2f, 0x72, 0x2d, 0x17, 0xd9, 0xee, 0x24, 0xb0, 0x76, 0x81, 0xcb, 0xb0, 0x57, 0x7b, 0x05, 0xd5,
	0x7d, 0x8a, 0x28, 0x50, 0xf9, 0xe4, 0x45, 0x5e, 0xcc, 0x43, 0xf5, 0x88, 0xd4, 0x40, 0x9e, 0xd9,
	0x51, 0xb4, 0xe0, 0xa1, 0xa3, 0x4a, 0xda, 0x7b, 0x80, 0xd9, 0xda, 0xde, 0xb9, 0xa1, 0xe1, 0x3f,
	0x70, 0xd2, 0x80, 0x82, 0xe7, 0x20, 0xb7, 0x12, 0x2b, 0x78, 0x8e, 0x60, 0xe5, 0x7b, 0xcb, 0x47,
	0x64, 0x9c, 0xb2, 0xca, 0xb0, 0xb6, 0x4e, 0x95, 0x09, 0x43, 0x5e, 0x43, 0xe9, 0xde, 0x8e, 0x12,
	0x55, 0x4a, 0xaf, 0x75, 0xc8, 0x30, 0xf5, 0x8c, 0x61, 0x03, 0xb9, 0x06, 0x25, 0xc0, 0x73, 0x77,
	0x9e, 0xff, 0xc0, 0x71, 0xa7, 0xd2, 0x3b, 0x3b, 0xec, 0xcf, 0xd9, 0x30, 0x08, 0xf6, 0xb1, 0xf6,
	0x43, 0x02, 0x99, 0x71, 0xbe, 0x41, 0x9a, 0xe7, 0x50, 0x09, 0x39, 0xdf, 0xdc, 0xed, 0xb9, 0x96,
	0x05, 0x34, 0x1c, 0x72, 0x99, 0x3a, 0x55, 0x40, 0xa7, 0x5e, 0x1c, 0xee, 0xcd, 0x86, 0x31, 0xc8,
	0x8d, 0x22, 0x6d, 0xa8, 0x18, 0xd1, 0x4d, 0x6c, 0x87, 0x31, 0xfa, 0x2b, 0xb3, 0x0c, 0x92, 0xb7,
	0x40, 0x96, 0xdb, 0x30, 0x74, 0xfd, 0xf8, 0x2e, 0xe5, 0xec, 0x6f, 0x37, 0xed, 0x52, 0x47, 0xea,
	0xd6, 0x99, 0x9a, 0x56, 0x12, 0xb6, 0x93, 0xed, 0x86, 0x7c, 0x80, 0xda, 0x81, 0xb2, 0xa8, 0x7d,
	0xdc, 0x29, 0xfe, 0x41, 0x9a, 0x92, 0x4b, 0x8b, 0xb4, 0x56, 0x22, 0x0d, 0x3f, 0x55, 0x05, 0x8a,
	0xd6, 0x62, 0xaa, 0x1e, 0x69, 0x75, 0x50, 0x3e, 0x72, 0xcf, 0x17, 0x05, 0xe6, 0x3e, 0x69, 0x5e,
	0x0e, 0xff, 0xca, 0xf0, 0x4b, 0xa8, 0x26, 0x56, 0xe5, 0x76, 0x9f, 0xfe, 0xce, 0x16, 0x26, 0x87,
	0x69, 0xa4, 0x7d, 0x85, 0x1a, 0x1a, 0x30, 0xb4, 0x37, 0xf8, 0xb7, 0x5f, 0x83, 0xec, 0x39, 0xae,
	0x1f, 0x7b, 0xf1, 0x0e, 0xef, 0x35, 0x7a, 0xcf, 0x0f, 0x37, 0x0c, 0x92, 0x87, 0x66, 0xa4, 0x2d,
	0x6c, 0xdf, 0xfc, 0x0f, 0xb7, 0xdf, 0x7c, 0x2b, 0x42, 0xf3, 0x97, 0x85, 0x04, 0xa0, 0x4c, 0x87,
	0xf3, 0xf1, 0x74, 0xa2, 0x1e, 0x89, 0x3f, 0x79, 0xc8, 0xf4, 0x5b, 0x01, 0x24, 0xa2, 0x42, 0xed,
	0x66, 0x34, 0x37, 0xcd, 0x2c, 0x53, 0x20, 0x0d, 0x80, 0x05, 0x65, 0x19, 0x2e, 0x62, 0x3b, 0xed,
	0xe3, 0x6c, 0x89, 0xd4, 0xa1, 0x3a, 0xa4, 0x6c, 0xce, 0x10, 0x1e, 0x93, 0x13, 0xa8, 0x2f, 0x74,
	0xa6, 0xe7, 0xa9, 0x32, 0x21, 0xd0, 0x18, 0xeb, 0x16, 0x35, 0xf3, 0x5c, 0x45, 0xac, 0xe8, 0x1b,
	0xb7, 0x53, 0x01, 0x64, 0xb1, 0xa2, 0x6f, 0xb0, 0x01, 0xa3, 0x02, 0x56, 0xb3, 0x8d, 0x03, 0x84,
	0x20, 0x5e, 0x96, 0xa5, 0x4f, 0x2c, 0xec, 0x55, 0x48, 0x13, 0x94, 0x11, 0xed, 0xcf, 0x2d, 0x9d,
	0x19, 0x22, 0x51, 0x23, 0x2d, 0x68, 0x8e, 0xf5, 0x21, 0x3d, 0x4c, 0xd6, 0x85, 0xb8, 0x19, 0x35,
	0x45, 0xdc, 0x10, 0xa7, 0xac, 0xe9, 0x50, 0x17, 0xa0, 0x29, 0x96, 0x99, 0x86, 0x69, 0xa2, 0x10,
	0x15, 0x85, 0x4c, 0xc7, 0x78, 0xe7, 0x44, 0x9c, 0x35, 0x46, 0x23, 0x3a, 0x42, 0x86, 0x44, 0xd4,
	0x3e, 0xcf, 0x07, 0x78, 0xb5, 0x25, 0xc0, 0x8c, 0x5a, 0xd8, 0x78, 0x2a, 0x00, 0x9d, 0x24, 0x0b,
	0xff, 0x13, 0x6e, 0x8d, 0xe9, 0x70, 0x42, 0xb3, 0xcc, 0x99, 0x28, 0xdf, 0x50, 0x13, 0x7b, 0xcf,
	0x13, 0xab, 0x12, 0xee, 0x6d, 0x71, 0x41, 0xb4, 0x2d, 0x10, 0xfe, 0x7f, 0x5f, 0xc6, 0x4f, 0x76,
	0xf5, 0x33, 0x00, 0x00, 0xff, 0xff, 0xff, 0xb4, 0x20, 0xf6, 0x55, 0x05, 0x00, 0x00,
}
